// ── API Key ───────────────────────────────────────────────────────────────────
function getApiKey() {
  return localStorage.getItem('claude_api_key') || (typeof DEFAULT_API_KEY !== 'undefined' ? DEFAULT_API_KEY : '');
}

// ── Market Configurations ────────────────────────────────────────────────────
const FIXED_MARKETS = ['Internacional', 'LATAM', 'CAM'];

const MARKETS = {
  UE: {
    nombre: 'Union Europea', idioma: 'en', flag: '🇪🇺',
    moca_por_material: {
      abs: 'Regulation (EU) 10/2011 — ABS/acrylic plastics in contact with food',
      pp: 'Regulation (EU) 10/2011 — Polypropylene (PP) in contact with food',
      ps: 'Regulation (EU) 10/2011 — Polystyrene (PS) in contact with food',
      silicona: 'Regulation (EU) 10/2011 — Food-grade silicone',
      acero: 'EN 1811 / EN 12020 — Stainless steel in contact with food',
      vidrio: 'Directive 84/500/EEC — Glass in contact with food',
      metal: 'EN 1811 / EN 12020 — Metal articles in contact with food',
    },
    moca_base: [
      'Regulation (EC) 1935/2004 — General framework for materials in contact with food',
      'Regulation (EC) 2023/2006 — Good manufacturing practices for FCM',
    ],
    juguetes: [
      'Directive 2009/48/EC — Safety of toys',
      'EN 71-1:2014+A1:2018 — Physical and mechanical properties',
      'EN 71-2:2020 — Flammability',
      'EN 71-3:2019+A1:2021 — Migration of certain elements',
      'EN 71-9 — Organic chemical compounds',
    ],
    electrica: [
      'Directive 2014/35/EU (LVD) — Low voltage',
      'Directive 2014/30/EU (EMC) — Electromagnetic compatibility',
      'EN 62368-1 — Audio/video and IT equipment safety',
      'Regulation (EU) 2023/1542 — Batteries and accumulators',
    ],
    quimica_base: ['REACH (EC) 1907/2006 — Restriction of SVHC substances, Annex XVII'],
    quimica_elec: ['RoHS 2011/65/EU + 2015/863/EU — Restriction of hazardous substances in electrical equipment'],
    etiquetado_base: [
      'FCM symbol (fork + glass) on all parts with direct food contact',
      'Name and address of manufacturer or EU importer',
      'CE marking mandatory (Directive 2009/48/EC + LVD if applicable)',
      'Product reference and batch/lot number',
      'Country of manufacture',
      'Warnings in the language of the country of sale (EN, ES, FR, DE, IT, etc.)',
      'WEEE symbol if product contains electronic components',
    ],
    doc: 'EU Declaration of Conformity (DoC)',
    retencion: '10 years (Art. 21 Directive 2009/48/EC)',
    ensayos_moca: {
      abs: [
        { ensayo: 'Overall migration (OML) — simulants D1, D2, E per intended use', norma: 'Reg. (EU) 10/2011, Art. 12 — Limit 10 mg/dm² or 60 mg/kg', frecuencia: 'Per batch / change of resin supplier' },
        { ensayo: 'Specific migration of ABS additives and monomers (SML)', norma: 'Reg. (EU) 10/2011, Annexes I and II — Individual limits per substance', frecuencia: 'Per formulation / change of composition' },
        { ensayo: 'Migration of heavy metals in accessible parts (Pb, Cd, Cr VI, Ba, Co, Ni)', norma: 'EN 71-3:2019+A1:2021 / EN 13130 series', frecuencia: 'Per production batch' },
        { ensayo: 'Organoleptic test — odour and taste verification', norma: 'Reg. (EC) 1935/2004, Art. 3 — Must not alter food organoleptically', frecuencia: 'Per formulation' },
      ],
      pp: [
        { ensayo: 'PP overall migration (OML) — simulants per use', norma: 'Reg. (EU) 10/2011, Art. 12', frecuencia: 'Per batch' },
        { ensayo: 'Specific migration of authorised PP additives', norma: 'Reg. (EU) 10/2011, Annex I', frecuencia: 'Per formulation' },
      ],
      silicona: [{ ensayo: 'Food-grade silicone migration in food simulants', norma: 'Reg. (EU) 10/2011 / LFGB Sec. 30 (Germany)', frecuencia: 'Per supplier / formulation' }],
      acero: [{ ensayo: 'Nickel (Ni) and chromium (Cr) migration in stainless steel', norma: 'EN 1811:2023 / EN 12020', frecuencia: 'Per supplier' }],
    },
    normas_seg: { mecanico: 'EN 71-1:2014+A1:2018', inflamabilidad: 'EN 71-2:2020', elementos: 'EN 71-3:2019+A1:2021', bordes: 'EN 71-1:2014+A1:2018' },
  },

  USA: {
    nombre: 'United States', idioma: 'en', flag: '🇺🇸',
    moca_por_material: {
      abs: '21 CFR 177.1010 — ABS and modified acrylic plastics in contact with food',
      pp: '21 CFR 177.1520 — Olefin polymers (PP/PE) in contact with food',
      ps: '21 CFR 177.1640 — Polystyrene and rubber-modified polystyrene in contact with food',
      silicona: '21 CFR 177.2600 — Rubber/silicone articles for repeated use in contact with food',
      acero: '21 CFR 177.2800 — Stainless steel for food use',
      metal: '21 CFR 177.2800 — Metal articles for food contact',
    },
    moca_base: [
      'FDA 21 CFR Subchapter B — Regulatory framework for food contact substances',
      'FDA FCS Notification Program — Notification program for new food contact substances',
    ],
    juguetes: [
      'CPSIA 2008 — Consumer Product Safety Improvement Act',
      'ASTM F963-23 (16 CFR Part 1250) — Standard Consumer Safety Specification for Toy Safety',
      '16 CFR Part 1303 — Ban on lead-containing paint (max 90 ppm)',
      '16 CFR Part 1307 — Prohibition of phthalates in children\'s toys',
      '16 CFR Part 1501 — Small parts identification for children under 3 years',
      'CPSIA Sec. 108 — Tracking labels on children\'s products',
    ],
    electrica: [
      'UL 62368-1 — Audio/video and IT equipment safety',
      'FCC Part 15 (Class B) — Unintentional radio frequency devices',
      'UL 8750 — LED lighting equipment',
      'CPSC Recess Act 2022 — Button cell battery safety in children\'s products',
    ],
    quimica_base: [
      'CPSIA Sec. 101 — Total lead in substrate of children\'s products (max 100 ppm)',
      '16 CFR Part 1307 — Restricted phthalates in toys and childcare articles',
      'California Proposition 65 — List of carcinogens and reproductive toxicants (if sold in CA)',
    ],
    quimica_elec: ['TSCA — Toxic Substances Control Act (chemical substance inventory)'],
    etiquetado_base: [
      'FCM symbol (fork + glass) on all parts with direct food contact',
      'Name and address of US importer or manufacturer',
      'Country of origin (Made in...) — 19 CFR 134 (US Customs)',
      'CPSIA Tracking Label — Manufacturer, production date, batch and country of origin (Sec. 108)',
      'Age group: "3+" or "For ages 3 and up" if applicable',
      'FCC declaration on product or packaging if electronics are included',
      'Choking hazard warning if small parts: "WARNING: CHOKING HAZARD — Small parts. Not for children under 3 years."',
    ],
    doc: 'CPSIA General Certificate of Conformity (GCC)',
    retencion: '5 years (CPSIA)',
    ensayos_moca: {
      abs: [
        { ensayo: 'Extraction in food simulants for ABS (modified acrylic)', norma: '21 CFR 177.1010 — Condition tables per food type and use temperature', frecuencia: 'Initial and upon formulation or supplier change' },
        { ensayo: 'Total extractables soluble in chloroform', norma: '21 CFR 177.1010(b) — Extractive limits per condition of use', frecuencia: 'Per production batch' },
        { ensayo: 'Total lead in substrate (children\'s product)', norma: 'CPSIA Sec. 101 / CPSC-CH-E1002-08 — Limit 100 ppm total', frecuencia: 'Per production batch' },
        { ensayo: 'Lead in surface coatings / paint', norma: '16 CFR 1303 / CPSC-CH-E1003-09 — Limit 90 ppm in paint', frecuencia: 'Per paint formulation' },
        { ensayo: 'Restricted phthalates (DEHP, DBP, BBP, DINP, DPENP, DHEXP, DCHP, DIBP)', norma: '16 CFR Part 1307 / CPSC-CH-C1001-09 — Limit 0.1% per phthalate', frecuencia: 'Per plastic material formulation' },
      ],
      pp: [{ ensayo: 'PP extraction in simulants per condition of use', norma: '21 CFR 177.1520', frecuencia: 'Initial and upon change' }],
    },
    normas_seg: { mecanico: 'ASTM F963-23', inflamabilidad: 'ASTM F963-23 Sec. 4.2', elementos: 'ASTM F963-23 / CPSC-CH-E1003-09', bordes: 'ASTM F963-23' },
  },

  Australia: {
    nombre: 'Australia', idioma: 'en', flag: '🇦🇺',
    moca_por_material: {
      abs: 'FSANZ Standard 1.4.1 — ABS in contact with food (EU Reg. 10/2011 accepted as technical reference)',
      pp: 'FSANZ Standard 1.4.1 — PP in contact with food',
      silicona: 'FSANZ Standard 1.4.1 — Food-grade silicone',
      acero: 'FSANZ Standard 1.4.1 — Stainless steel in contact with food',
    },
    moca_base: [
      'FSANZ Act 1991 — Food Standards Australia New Zealand Act, general framework',
      'Australia New Zealand Food Standards Code — Standard 3.2.2 / 3.2.3',
      'FSANZ Policy Guidance on Food Contact Materials — accepts EU Reg. 10/2011 as technical reference',
    ],
    juguetes: [
      'Australian Consumer Law (ACL) — Competition and Consumer Act 2010, Schedule 2',
      'AS/NZS ISO 8124.1:2019 — Physical and mechanical properties of toys',
      'AS/NZS ISO 8124.2:2015 — Flammability of toys',
      'AS/NZS ISO 8124.3:2020 — Migration of certain elements in toys',
      'Consumer Protection Notice No. 9/2003 — Toys for children under 36 months',
    ],
    electrica: [
      'EESS — Electrical Equipment Safety System (mandatory registration)',
      'RCM Mark — Regulatory Compliance Mark (mandatory for electrical products)',
      'AS/NZS 62368.1:2018 — Audio/video and IT equipment safety',
      'ACMA — Australian Communications and Media Authority (EMC declaration)',
    ],
    quimica_base: [
      'Industrial Chemicals Act 2019 (AICIS) — Assessment of industrial chemicals',
      'AS/NZS ISO 8124.3:2020 — Migration of elements (Sb, As, Ba, Cd, Cr, Pb, Hg, Se)',
    ],
    quimica_elec: ['Battery Stewardship Council / B-cycle — Battery and accumulator disposal'],
    etiquetado_base: [
      'FCM symbol (fork + glass) on all parts with direct food contact',
      'Product name and description in English',
      'Australian importer: name, address and ABN mandatory (ACL)',
      'Country of origin — mandatory under ACL Country of Origin Food Labelling Standard 2016',
      'RCM Mark on product and packaging if electronics are included',
      'Age group: "3+" or "Suitable for ages 3 and up"',
      'ARL (Australasian Recycling Label) — recommended for recycling information',
      'Instructions for use and safety warnings in English',
    ],
    doc: 'ACMA Declaration of Conformity + EESS registration for electrical components',
    retencion: '7 years (general ACL recommendation)',
    ensayos_moca: {
      abs: [
        { ensayo: 'Overall migration in food simulants (FSANZ / EU Reg. 10/2011 as technical reference)', norma: 'FSANZ Standard 1.4.1 / EU Reg. 10/2011 Art. 12 — Limit 10 mg/dm²', frecuencia: 'Per batch / supplier change' },
        { ensayo: 'Specific ABS migration — formulation substances', norma: 'FSANZ / AICIS guidance / EU Reg. 10/2011 Annex I as reference', frecuencia: 'Per formulation' },
        { ensayo: 'Migration of heavy metals (Sb, As, Ba, Cd, Cr, Pb, Hg, Se)', norma: 'AS/NZS ISO 8124.3:2020', frecuencia: 'Per pigment and colorant formulation' },
      ],
      pp: [{ ensayo: 'PP overall migration', norma: 'FSANZ / EU Reg. 10/2011 reference', frecuencia: 'Per batch' }],
    },
    normas_seg: { mecanico: 'AS/NZS ISO 8124.1:2019', inflamabilidad: 'AS/NZS ISO 8124.2:2015', elementos: 'AS/NZS ISO 8124.3:2020', bordes: 'AS/NZS ISO 8124.1:2019' },
  },

  Brasil: {
    nombre: 'Brasil', idioma: 'pt', flag: '🇧🇷',
    moca_por_material: {
      abs: 'Resolução RDC n. 105/1999 (ANVISA) + RDC n. 56/2012 — Embalagens plásticas ABS em contato com alimentos',
      pp: 'Resolução RDC n. 105/1999 (ANVISA) — PP em contato com alimentos',
      silicona: 'Resolução n. 123/2001 (ANVISA) — Elastômeros e silicones em contato com alimentos',
      acero: 'Resolução RDC n. 91/2001 (ANVISA) — Aço inoxidável em contato com alimentos',
    },
    moca_base: [
      'Resolução RDC n. 91/2001 (ANVISA) — Critérios gerais para embalagens em contato com alimentos',
      'Resolução RDC n. 589/2021 (ANVISA) — Atualiza LMT para 10 mg/dm² (alinha com EU Reg. 10/2011)',
      'Resolução RDC n. 88/2016 (ANVISA) — Boas práticas de fabricação para MOCA',
    ],
    juguetes: [
      'ABNT NBR NM 300:2004 — Segurança de brinquedos (partes 1, 2 e 3)',
      'Portaria INMETRO 563/2016 — Regulamento técnico de qualidade para brinquedos (obrigatório)',
      'ABNT NBR 11136 — Brinquedos — requisitos de segurança',
    ],
    electrica: [
      'ABNT NBR IEC 62368-1 — Segurança de equipamentos audiovisuais e de tecnologia',
      'Resolução ANATEL — Homologação de produtos de telecomunicações',
      'INMETRO — Certificação obrigatória para produtos elétricos',
    ],
    quimica_base: [
      'Resolução RDC n. 56/2012 (ANVISA) — Listas positivas de substâncias plásticas para MOCA',
      'REACH (CE) 1907/2006 — Referência técnica para SVHC',
    ],
    quimica_elec: ['Resolução CONAMA 401/2008 — Limites de metais pesados em pilhas e baterias'],
    etiquetado_base: [
      'Símbolo de material em contato com alimentos (garfo + copo) em todas as peças com contato direto com alimento',
      'Rotulagem em português — obrigatório (RDC 360/2003 e RDC 259/2002)',
      'Nome e endereço do fabricante ou importador no Brasil com CNPJ',
      'País de fabricação',
      'Marca INMETRO se produto sujeito a certificação obrigatória',
      'Instruções de uso e advertências de segurança',
      'Composição do material (ex: plástico ABS)',
    ],
    doc: 'Declaração de Conformidade INMETRO (se certificação obrigatória)',
    retencion: '5 anos (prática recomendada ANVISA)',
    ensayos_moca: {
      abs: [
        { ensayo: 'Migração global (LMT) em simulantes alimentares', norma: 'Resolução RDC n. 105/1999 + RDC n. 589/2021 — LMT 10 mg/dm² ou 60 mg/kg', frecuencia: 'Por lote / mudança de fornecedor' },
        { ensayo: 'Migração específica de substâncias ABS (lista positiva ANVISA)', norma: 'Resolução RDC n. 56/2012 (ANVISA) — Lista positiva de substâncias plásticas', frecuencia: 'Por formulação' },
        { ensayo: 'Metais pesados em partes acessíveis', norma: 'ABNT NBR NM 300:2004 Parte 3 / Portaria INMETRO 563/2016', frecuencia: 'Por formulação de pigmentos' },
      ],
      pp: [{ ensayo: 'Migração global PP', norma: 'Resolução RDC n. 105/1999 (ANVISA)', frecuencia: 'A cada 2 anos' }],
    },
    normas_seg: { mecanico: 'ABNT NBR NM 300-1 / Portaria INMETRO 563/2016', inflamabilidad: 'ABNT NBR 11136', elementos: 'ABNT NBR NM 300-3 / Portaria INMETRO 563/2016', bordes: 'ABNT NBR NM 300-1 / Portaria INMETRO 563/2016' },
  },

  Colombia: {
    nombre: 'Colombia', idioma: 'es', flag: '🇨🇴',
    moca_por_material: {
      abs: 'Resolución 683/2012 (INVIMA) — Materiales plásticos en contacto con alimentos — ABS',
      pp: 'Resolución 683/2012 (INVIMA) — PP en contacto con alimentos',
      silicona: 'Resolución 683/2012 (INVIMA) — Materiales siliconados en contacto con alimentos',
      acero: 'Resolución 683/2012 (INVIMA) — Acero inoxidable en contacto con alimentos',
    },
    moca_base: [
      'Resolución 834/2013 (MINSALUD) — Utensilios, envases y equipos en contacto con alimentos',
      'Codex Alimentarius — Normas internacionales de referencia aplicadas en Colombia',
    ],
    juguetes: [
      'NTC 4894:2008 — Seguridad de juguetes (equivalente ISO 8124)',
      'Resolución SIC sobre juguetes — vigilancia y control de calidad',
    ],
    electrica: ['RETIE — Reglamento Técnico de Instalaciones Eléctricas (Resolución 90708/2013)', 'NTC-IEC 62368-1 — Seguridad equipos audiovisuales'],
    quimica_base: ['Resolución 1111/2017 (MINSALUD) — Evaluación del riesgo químico', 'REACH (CE) 1907/2006 — Referencia técnica internacional para SVHC'],
    quimica_elec: [],
    etiquetado_base: [
      'Símbolo de material en contacto con alimentos (tenedor + copa) en todas las partes con contacto directo',
      'Etiqueta en español — obligatorio en Colombia',
      'Nombre del producto y del fabricante o importador con NIT',
      'País de origen',
      'Instrucciones de uso y advertencias de seguridad',
      'Sello de conformidad ICONTEC o SIC si aplica',
      'Registro sanitario INVIMA si aplica',
    ],
    doc: 'Declaración de Conformidad ante SIC / ICONTEC',
    retencion: '5 años',
    ensayos_moca: {
      abs: [
        { ensayo: 'Migración global en simulantes alimentarios', norma: 'Resolución 683/2012 (INVIMA) — Límites según Codex / EU Reg. 10/2011 referencia', frecuencia: 'Por lote / cambio de proveedor' },
        { ensayo: 'Migración específica sustancias ABS', norma: 'Resolución 834/2013 / EU Reg. 10/2011 Anexo I como referencia técnica', frecuencia: 'Por formulación' },
        { ensayo: 'Metales pesados en partes accesibles', norma: 'NTC 4894-3:2008 (ISO 8124-3) — Sb, As, Ba, Cd, Cr, Pb, Hg, Se', frecuencia: 'Por formulación de pigmentos' },
      ],
      pp: [{ ensayo: 'Migración global PP', norma: 'Resolución 683/2012 (INVIMA)', frecuencia: 'Por lote' }],
    },
    normas_seg: { mecanico: 'NTC 4894-1:2008', inflamabilidad: 'NTC 4894-2:2008', elementos: 'NTC 4894-3:2008', bordes: 'NTC 4894-1:2008' },
  },

  Argentina: {
    nombre: 'Argentina', idioma: 'es', flag: '🇦🇷',
    moca_por_material: {
      abs: 'Resolución GMC 56/92 (MERCOSUR) + CAA Art. 184-212 — ABS en contacto con alimentos',
      pp: 'MERCOSUR GMC RES 32/2011 — PP en contacto con alimentos',
      silicona: 'Código Alimentario Argentino (CAA) — Silicona en contacto con alimentos',
      acero: 'CAA Art. 184 — Acero inoxidable AISI 304/316 en contacto con alimentos',
    },
    moca_base: [
      'Código Alimentario Argentino (CAA) — Capítulo IV: Utensilios, recipientes y envases',
      'MERCOSUR GMC RES 32/2011 — Reglamento técnico MERCOSUR sobre materiales plásticos MOCA',
    ],
    juguetes: [
      'Resolución 909/2005 (IRAM) — Seguridad de juguetes',
      'IRAM-ISO 8124 (partes 1, 2, 3) — Seguridad de juguetes',
      'Disposición ANMAT 4980/2005 — Requisitos de seguridad de juguetes',
    ],
    electrica: ['Resolución SIC 92/98 — Seguridad para productos eléctricos', 'IRAM-IEC 62368-1 — Seguridad de equipos de audio/video'],
    quimica_base: ['Ley 24.051 — Residuos peligrosos (sustancias químicas)', 'REACH (CE) 1907/2006 — Referencia técnica internacional para SVHC'],
    quimica_elec: [],
    etiquetado_base: [
      'Símbolo de material en contacto con alimentos (tenedor + copa) en todas las partes con contacto directo',
      'Etiqueta en español — obligatorio en Argentina',
      'Nombre del producto y del fabricante o importador con CUIT',
      'País de fabricación',
      'Sello IRAM si aplica certificación voluntaria',
      'Instrucciones de uso y advertencias de seguridad',
      'Número de partida o lote de producción',
    ],
    doc: 'Declaración de Conformidad IRAM / ANMAT según producto',
    retencion: '5 años',
    ensayos_moca: {
      abs: [
        { ensayo: 'Migración global en simulantes alimentarios (LMT)', norma: 'CAA / MERCOSUR GMC RES 32/2011 — Límite 10 mg/dm² (alineado con EU Reg. 10/2011)', frecuencia: 'Por lote / cambio de proveedor' },
        { ensayo: 'Migración específica sustancias ABS (lista positiva MERCOSUR)', norma: 'MERCOSUR GMC RES 32/2011 — Lista positiva regional', frecuencia: 'Por formulación' },
        { ensayo: 'Metales pesados en partes accesibles', norma: 'IRAM-ISO 8124-3 — Sb, As, Ba, Cd, Cr, Pb, Hg, Se', frecuencia: 'Por formulación de pigmentos' },
      ],
      pp: [{ ensayo: 'Migración global PP', norma: 'MERCOSUR GMC RES 32/2011 / CAA', frecuencia: 'Por lote' }],
    },
    normas_seg: { mecanico: 'IRAM-ISO 8124-1', inflamabilidad: 'IRAM-ISO 8124-2 / Disposición ANMAT 4980/2005', elementos: 'IRAM-ISO 8124-3', bordes: 'IRAM-ISO 8124-1' },
  },

  Peru: {
    nombre: 'Peru', idioma: 'es', flag: '🇵🇪',
    moca_por_material: {
      abs: 'NTP 399.165 — Materiales plásticos en contacto con alimentos — ABS',
      pp: 'NTP 399.165 — PP en contacto con alimentos',
      silicona: 'NTP 399.165 / Codex Alimentarius — Silicona en contacto con alimentos',
    },
    moca_base: [
      'NTP 399.165 — Norma Técnica Peruana sobre materiales en contacto con alimentos',
      'Codex Alimentarius — Normas internacionales de referencia',
      'EU Reg. 10/2011 — Referencia técnica aceptada por INDECOPI',
    ],
    juguetes: [
      'NTP-ISO 8124 (partes 1, 2, 3) — Seguridad de juguetes',
      'Decreto Supremo PRODUCE — Reglamentación de juguetes en el mercado peruano',
    ],
    electrica: ['NTP-IEC 62368-1 — Seguridad de equipos audiovisuales', 'Resolución MTC — Ministerio de Transportes y Comunicaciones'],
    quimica_base: ['Ley 28256 — Transporte de materiales y residuos peligrosos', 'REACH (CE) 1907/2006 — Referencia técnica para SVHC'],
    quimica_elec: [],
    etiquetado_base: [
      'Símbolo de material en contacto con alimentos (tenedor + copa) en todas las partes con contacto directo',
      'Etiqueta en español — obligatorio en Perú',
      'Nombre del producto y del fabricante o importador con RUC',
      'País de fabricación',
      'Instrucciones de uso y advertencias de seguridad',
      'Registro INDECOPI si aplica',
      'Número de lote de producción',
    ],
    doc: 'Declaración de Conformidad INDECOPI',
    retencion: '5 años',
    ensayos_moca: {
      abs: [
        { ensayo: 'Migración global en simulantes alimentarios', norma: 'NTP 399.165 / EU Reg. 10/2011 como referencia técnica aceptada — Límite 10 mg/dm²', frecuencia: 'Por lote / cambio de proveedor' },
        { ensayo: 'Migración específica sustancias ABS', norma: 'NTP 399.165 / Codex Alimentarius', frecuencia: 'Por formulación' },
        { ensayo: 'Metales pesados en partes accesibles', norma: 'NTP-ISO 8124-3 / DIGESA restricciones', frecuencia: 'Por formulación de pigmentos' },
      ],
      pp: [{ ensayo: 'Migración global PP', norma: 'NTP 399.165', frecuencia: 'Por lote' }],
    },
    normas_seg: { mecanico: 'NTP-ISO 8124-1', inflamabilidad: 'NTP-ISO 8124-2', elementos: 'NTP-ISO 8124-3', bordes: 'NTP-ISO 8124-1' },
  },

  Centroamerica: {
    nombre: 'Centroamerica', idioma: 'es', flag: '🌎',
    moca_por_material: {
      abs: 'RTCA 67.01.33:06 — Materiales plásticos en contacto con alimentos — ABS',
      pp: 'RTCA 67.01.33:06 — PP en contacto con alimentos',
      silicona: 'RTCA 67.01.33:06 — Materiales siliconados en contacto con alimentos',
    },
    moca_base: [
      'RTCA 67.01.33:06 — Reglamento Técnico Centroamericano — Materiales en contacto con alimentos',
      'Codex Alimentarius — Normas de referencia base para MOCA',
      'EU Reg. 10/2011 — Referencia técnica aceptada regionalmente',
    ],
    juguetes: [
      'RTCA 65.01.53:08 — Reglamento Técnico Centroamericano — Seguridad de juguetes',
      'ISO 8124 (partes 1, 2, 3) — Referencia técnica',
    ],
    electrica: ['Normativas nacionales de cada país de Centroamérica', 'IEC 62368-1 — Referencia técnica internacional'],
    quimica_base: ['RTCA 67.04.54:10 — Límites de contaminantes en alimentos', 'REACH (CE) 1907/2006 — Referencia técnica para SVHC'],
    quimica_elec: [],
    etiquetado_base: [
      'Símbolo de material en contacto con alimentos (tenedor + copa) en todas las partes con contacto directo',
      'Etiqueta en español — obligatorio en todos los países de Centroamérica',
      'Nombre del producto y del fabricante o importador local',
      'País de origen',
      'Instrucciones de uso y advertencias de seguridad',
      'Registro sanitario nacional según el país de distribución',
    ],
    doc: 'Declaración de Conformidad del fabricante con RTCAs aplicables',
    retencion: '5 años (práctica recomendada regional)',
    ensayos_moca: {
      abs: [
        { ensayo: 'Migración global en simulantes (metodología RTCA / Codex)', norma: 'RTCA 67.01.33:06 / Codex Alimentarius — Límite referencia EU 10 mg/dm²', frecuencia: 'Por lote / cambio de proveedor' },
        { ensayo: 'Migración específica sustancias ABS', norma: 'RTCA 67.01.33:06 / EU Reg. 10/2011 Anexo I como referencia', frecuencia: 'Por formulación' },
      ],
      pp: [{ ensayo: 'Migración global PP', norma: 'RTCA 67.01.33:06', frecuencia: 'Por lote' }],
    },
    normas_seg: { mecanico: 'RTCA 65.01.53:08 / ISO 8124-1', inflamabilidad: 'RTCA 65.01.53:08 / EN 71-2', elementos: 'RTCA 65.01.53:08 / EN 71-3', bordes: 'RTCA 65.01.53:08 / ISO 8124-1' },
  },

  // ── Consolidated expediente markets ─────────────────────────────────────────

  Internacional: {
    nombre: 'Internacional', nombre_en: 'International', idioma: 'en', flag: '🌐',
    subtitulo: 'European Union · United States · Australia',
    moca_por_material: {
      abs: 'EU Reg. 10/2011 (primary) / 21 CFR 177.1010 (USA) / FSANZ Std. 1.4.1 (AU) — ABS plastics in food contact',
      pp: 'EU Reg. 10/2011 / 21 CFR 177.1520 / FSANZ Std. 1.4.1 — Polypropylene in food contact',
      ps: 'EU Reg. 10/2011 / 21 CFR 177.1640 / FSANZ — Polystyrene in food contact',
      silicona: 'EU Reg. 10/2011 / 21 CFR 177.2600 / FSANZ — Food-grade silicone',
      acero: 'EN 1811 / 21 CFR 177.2800 / FSANZ — Stainless steel in food contact',
      vidrio: 'Directive 84/500/EEC / FDA / FSANZ — Glass in food contact',
      metal: 'EN 1811 / 21 CFR 177.2800 / FSANZ — Metal articles in food contact',
    },
    moca_base: [
      'Regulation (EC) 1935/2004 — General EU framework for food contact materials',
      'Regulation (EC) 2023/2006 — Good manufacturing practices for FCM (EU)',
      'FDA 21 CFR Subchapter B — Food contact substances regulatory framework (USA)',
      'FSANZ Act 1991 / Food Standards Code Std. 3.2.2 — Food contact framework (Australia)',
    ],
    juguetes: [
      'Directive 2009/48/EC + EN 71-1/2/3/9 — Toy safety (EU)',
      'CPSIA 2008 + ASTM F963-23 (16 CFR Part 1250) — Consumer toy safety (USA)',
      'Australian Consumer Law (ACL) + AS/NZS ISO 8124.1/2/3 — Toy safety (Australia)',
      '16 CFR Part 1303 — Lead paint ban, max 90 ppm (USA)',
      '16 CFR Part 1307 — Restricted phthalates (USA)',
      '16 CFR Part 1501 — Small parts, children under 3 (USA)',
    ],
    electrica: [
      'Directive 2014/35/EU (LVD) + EN 62368-1 — Low voltage (EU)',
      'Directive 2014/30/EU (EMC) — Electromagnetic compatibility (EU)',
      'UL 62368-1 + FCC Part 15 Class B — Electrical & EMC (USA)',
      'EESS + RCM Mark + AS/NZS 62368.1 — Electrical safety (Australia)',
      'Regulation (EU) 2023/1542 / CPSC Recess Act 2022 — Battery safety',
    ],
    quimica_base: [
      'REACH (EC) 1907/2006 — Restriction of SVHC substances, Annex XVII (EU)',
      'RoHS 2011/65/EU — Restriction of hazardous substances in electrical equipment',
      'CPSIA Sec. 101 — Total lead max 100 ppm (USA children\'s products)',
      '16 CFR Part 1307 — Phthalates restriction (USA)',
      'California Prop. 65 — Carcinogens and reproductive toxicants (if sold in CA)',
      'Industrial Chemicals Act 2019 (AICIS) — Chemical substance assessment (Australia)',
    ],
    quimica_elec: [
      'RoHS 2011/65/EU + 2015/863/EU — Hazardous substances in electrical equipment',
      'TSCA — Toxic Substances Control Act (USA)',
      'Battery Stewardship Council / B-cycle (Australia)',
    ],
    etiquetado_base: [
      'FCM symbol (fork + glass) on all parts with direct food contact',
      'CE marking mandatory (EU — Directive 2009/48/EC + LVD if applicable)',
      'CPSIA Tracking Label — Manufacturer, production date, batch, country of origin (USA)',
      'RCM Mark on product and packaging if electronics included (Australia)',
      'Name and address of EU importer / US importer / AU importer (ABN) on packaging',
      'Country of manufacture — mandatory for all 3 markets',
      'Warnings in language of the country of sale (multilingual where required)',
      'Age group labelling: "3+" / "For ages 3 and up" if applicable',
      'Choking hazard warning for small parts (USA): "WARNING: CHOKING HAZARD"',
      'WEEE symbol if product contains electronic components (EU)',
    ],
    doc: 'EU Declaration of Conformity (DoC) + CPSIA General Certificate of Conformity (GCC) + ACMA/EESS Declaration (AU)',
    retencion: '10 years (EU — most stringent; covers USA 5yr and AU 7yr requirements)',
    ensayos_moca: {
      abs: [
        { ensayo: 'Overall migration (OML) in food simulants D1, D2, E', norma: 'EU Reg. 10/2011 Art. 12 — Limit 10 mg/dm² or 60 mg/kg (accepted reference for USA/AU)', frecuencia: 'Per batch / supplier change' },
        { ensayo: 'Specific migration of ABS additives and monomers (SML)', norma: 'EU Reg. 10/2011 Annexes I & II / 21 CFR 177.1010 (USA)', frecuencia: 'Per formulation change' },
        { ensayo: 'Total extractables in chloroform (ABS)', norma: '21 CFR 177.1010(b) — Extraction limits per condition of use (USA)', frecuencia: 'Per production batch' },
        { ensayo: 'Total lead in substrate (children\'s product)', norma: 'CPSIA Sec. 101 / CPSC-CH-E1002-08 — Max 100 ppm (USA)', frecuencia: 'Per production batch' },
        { ensayo: 'Lead in surface coatings / paint', norma: '16 CFR 1303 / EN 71-3 — Max 90 ppm paint / migration limits EU', frecuencia: 'Per paint formulation' },
        { ensayo: 'Restricted phthalates (DEHP, DBP, BBP, DINP, DPENP, DHEXP, DCHP, DIBP)', norma: '16 CFR Part 1307 — Max 0.1% per phthalate (USA/EU)', frecuencia: 'Per plastic formulation' },
        { ensayo: 'Heavy metals migration in accessible parts (Pb, Cd, Cr, Ba, Sb, As, Hg, Se)', norma: 'EN 71-3:2019+A1:2021 (EU) / AS/NZS ISO 8124.3 (AU) / ASTM F963-23 (USA)', frecuencia: 'Per pigment formulation' },
        { ensayo: 'Organoleptic test — odour and taste', norma: 'Reg. (EC) 1935/2004 Art. 3', frecuencia: 'Per formulation' },
      ],
      pp: [
        { ensayo: 'PP overall migration in food simulants', norma: 'EU Reg. 10/2011 Art. 12 / 21 CFR 177.1520 / FSANZ Std. 1.4.1', frecuencia: 'Per batch' },
        { ensayo: 'Specific migration of PP additives', norma: 'EU Reg. 10/2011 Annex I', frecuencia: 'Per formulation' },
      ],
      silicona: [{ ensayo: 'Food-grade silicone migration in food simulants', norma: 'EU Reg. 10/2011 / 21 CFR 177.2600 / FSANZ', frecuencia: 'Per supplier / formulation' }],
      acero: [{ ensayo: 'Nickel (Ni) and chromium (Cr) migration', norma: 'EN 1811:2023 / 21 CFR 177.2800 / FSANZ', frecuencia: 'Per supplier' }],
    },
    normas_seg: { mecanico: 'EN 71-1:2014+A1:2018 / ASTM F963-23 / AS/NZS ISO 8124.1', inflamabilidad: 'EN 71-2:2020 / ASTM F963-23 Sec. 4.2 / AS/NZS ISO 8124.2', elementos: 'EN 71-3:2019+A1:2021 / ASTM F963-23 / AS/NZS ISO 8124.3', bordes: 'EN 71-1 / ASTM F963-23 / AS/NZS ISO 8124.1' },
  },

  LATAM: {
    nombre: 'LATAM', idioma: 'es', flag: '🌎',
    subtitulo: 'Brasil · Colombia · Argentina · Perú',
    moca_por_material: {
      abs: 'Brasil: RDC n. 105/1999 + RDC n. 56/2012 (ANVISA) | Colombia: Res. 683/2012 (INVIMA) | Argentina: GMC RES 32/2011 (MERCOSUR) + CAA | Perú: NTP 399.165 — ABS en contacto con alimentos',
      pp: 'Brasil: RDC n. 105/1999 (ANVISA) | Colombia: Res. 683/2012 (INVIMA) | Argentina: GMC RES 32/2011 | Perú: NTP 399.165 — PP en contacto con alimentos',
      silicona: 'Brasil: Res. n. 123/2001 (ANVISA) | Colombia: Res. 683/2012 (INVIMA) | Argentina: CAA | Perú: NTP 399.165 — Silicona grado alimenticio',
      acero: 'Brasil: RDC n. 91/2001 (ANVISA) | Argentina: CAA Art. 184 (AISI 304/316) | Colombia: Res. 683/2012 | Perú: NTP 399.165 — Acero inoxidable en contacto con alimentos',
    },
    moca_base: [
      '🇧🇷 Brasil: RDC n. 91/2001 + RDC n. 589/2021 (ANVISA) — LMT 10 mg/dm², alineado con EU Reg. 10/2011',
      '🇨🇴 Colombia: Resolución 834/2013 (MINSALUD) + Res. 683/2012 (INVIMA) — Envases y utensilios en contacto con alimentos',
      '🇦🇷 Argentina: Código Alimentario Argentino (CAA) Cap. IV + MERCOSUR GMC RES 32/2011',
      '🇵🇪 Perú: NTP 399.165 (INDECOPI) + Codex Alimentarius — EU Reg. 10/2011 aceptada como referencia técnica',
    ],
    juguetes: [
      '🇧🇷 Brasil: ABNT NBR NM 300:2004 (partes 1, 2, 3) + Portaria INMETRO 563/2016 (obligatoria)',
      '🇨🇴 Colombia: NTC 4894:2008 — Seguridad de juguetes (equivalente ISO 8124)',
      '🇦🇷 Argentina: IRAM-ISO 8124 (partes 1, 2, 3) + Disposición ANMAT 4980/2005',
      '🇵🇪 Perú: NTP-ISO 8124 (partes 1, 2, 3) + Decreto Supremo PRODUCE',
    ],
    electrica: [
      '🇧🇷 Brasil: ABNT NBR IEC 62368-1 + Certificación obligatoria INMETRO',
      '🇨🇴 Colombia: RETIE (Res. 90708/2013) + NTC-IEC 62368-1',
      '🇦🇷 Argentina: Resolución SIC 92/98 + IRAM-IEC 62368-1',
      '🇵🇪 Perú: NTP-IEC 62368-1 + Resolución MTC',
    ],
    quimica_base: [
      '🇧🇷 Brasil: RDC n. 56/2012 (ANVISA) — Lista positiva de sustancias plásticas MOCA',
      '🇨🇴 Colombia: Resolución 1111/2017 (MINSALUD) — Evaluación del riesgo químico',
      '🇦🇷 Argentina: Ley 24.051 — Residuos peligrosos / sustancias químicas',
      '🇵🇪 Perú: Ley 28256 — Transporte de materiales y residuos peligrosos',
      'REACH (CE) 1907/2006 — Referencia técnica internacional para SVHC (todos los mercados)',
    ],
    quimica_elec: [
      '🇧🇷 Brasil: Resolución CONAMA 401/2008 — Límites de metales pesados en pilas y baterías',
    ],
    etiquetado_base: [
      'Símbolo de material en contacto con alimentos (tenedor + copa) en todas las partes con contacto directo',
      '🇧🇷 Brasil: Rotulagem em português — obrigatório (RDC 360/2003). CNPJ do importador. Marca INMETRO se aplicável',
      '🇨🇴 Colombia: Etiqueta en español con NIT del importador. Sello INVIMA si aplica',
      '🇦🇷 Argentina: Etiqueta en español con CUIT del importador. Sello IRAM si aplica',
      '🇵🇪 Perú: Etiqueta en español con RUC del importador. Registro INDECOPI si aplica',
      'País de fabricación — obligatorio en todos los mercados LATAM',
      'Instrucciones de uso y advertencias de seguridad en el idioma del mercado de destino',
      'Número de lote o partida de producción',
    ],
    doc: '🇧🇷 Declaração de Conformidade INMETRO | 🇨🇴 Declaración de Conformidad SIC/ICONTEC | 🇦🇷 Declaración de Conformidad IRAM/ANMAT | 🇵🇪 Declaración de Conformidad INDECOPI',
    retencion: '5 años (práctica recomendada en todos los mercados LATAM)',
    ensayos_moca: {
      abs: [
        { ensayo: 'Migración global (LMT) en simulantes alimentarios', norma: '🇧🇷 RDC 589/2021 (ANVISA) | 🇨🇴 Res. 683/2012 (INVIMA) | 🇦🇷 GMC RES 32/2011 | 🇵🇪 NTP 399.165 — Límite 10 mg/dm²', frecuencia: 'Por lote / cambio de proveedor' },
        { ensayo: 'Migración específica de sustancias ABS (listas positivas regionales)', norma: '🇧🇷 RDC n. 56/2012 (ANVISA) | 🇦🇷 GMC RES 32/2011 | EU Reg. 10/2011 Anexo I (referencia)', frecuencia: 'Por formulación' },
        { ensayo: 'Metales pesados en partes accesibles (Sb, As, Ba, Cd, Cr, Pb, Hg, Se)', norma: '🇧🇷 ABNT NBR NM 300-3 / INMETRO 563 | 🇨🇴 NTC 4894-3 | 🇦🇷 IRAM-ISO 8124-3 | 🇵🇪 NTP-ISO 8124-3', frecuencia: 'Por formulación de pigmentos' },
      ],
      pp: [
        { ensayo: 'Migración global PP en simulantes', norma: '🇧🇷 RDC 105/1999 | 🇨🇴 Res. 683/2012 | 🇦🇷 GMC RES 32/2011 | 🇵🇪 NTP 399.165', frecuencia: 'Por lote' },
      ],
      silicona: [{ ensayo: 'Migración silicona grado alimenticio en simulantes', norma: '🇧🇷 Res. 123/2001 (ANVISA) / EU Reg. 10/2011 referencia regional', frecuencia: 'Por proveedor / formulación' }],
    },
    normas_seg: { mecanico: '🇧🇷 ABNT NBR NM 300-1/INMETRO 563 | 🇨🇴 NTC 4894-1 | 🇦🇷 IRAM-ISO 8124-1 | 🇵🇪 NTP-ISO 8124-1', inflamabilidad: '🇧🇷 ABNT NBR 11136 | 🇦🇷 IRAM-ISO 8124-2 | 🇨🇴🇵🇪 ISO 8124-2', elementos: '🇧🇷 ABNT NBR NM 300-3/INMETRO 563 | 🇨🇴 NTC 4894-3 | 🇦🇷 IRAM-ISO 8124-3 | 🇵🇪 NTP-ISO 8124-3', bordes: 'ISO 8124-1 / normas nacionales equivalentes' },
  },

  CAM: {
    nombre: 'Centroamérica', idioma: 'es', flag: '🌎',
    subtitulo: 'Guatemala · El Salvador · Honduras · Nicaragua · Costa Rica · Panamá',
    moca_por_material: {
      abs: 'RTCA 67.01.33:06 — Materiales plásticos en contacto con alimentos — ABS',
      pp: 'RTCA 67.01.33:06 — PP en contacto con alimentos',
      silicona: 'RTCA 67.01.33:06 — Materiales siliconados en contacto con alimentos',
    },
    moca_base: [
      'RTCA 67.01.33:06 — Reglamento Técnico Centroamericano — Materiales en contacto con alimentos',
      'Codex Alimentarius — Normas de referencia base para MOCA',
      'EU Reg. 10/2011 — Referencia técnica aceptada regionalmente',
    ],
    juguetes: [
      'RTCA 65.01.53:08 — Reglamento Técnico Centroamericano — Seguridad de juguetes',
      'ISO 8124 (partes 1, 2, 3) — Referencia técnica internacional',
    ],
    electrica: ['Normativas nacionales de cada país de Centroamérica', 'IEC 62368-1 — Referencia técnica internacional'],
    quimica_base: ['RTCA 67.04.54:10 — Límites de contaminantes en alimentos', 'REACH (CE) 1907/2006 — Referencia técnica para SVHC'],
    quimica_elec: [],
    etiquetado_base: [
      'Símbolo de material en contacto con alimentos (tenedor + copa) en todas las partes con contacto directo',
      'Etiqueta en español — obligatorio en todos los países de Centroamérica',
      'Nombre del producto y del fabricante o importador local',
      'País de origen',
      'Instrucciones de uso y advertencias de seguridad',
      'Registro sanitario nacional según el país de distribución',
    ],
    doc: 'Declaración de Conformidad del fabricante con RTCAs aplicables',
    retencion: '5 años (práctica recomendada regional)',
    ensayos_moca: {
      abs: [
        { ensayo: 'Migración global en simulantes (metodología RTCA / Codex)', norma: 'RTCA 67.01.33:06 / Codex Alimentarius — Límite referencia EU 10 mg/dm²', frecuencia: 'Por lote / cambio de proveedor' },
        { ensayo: 'Migración específica sustancias ABS', norma: 'RTCA 67.01.33:06 / EU Reg. 10/2011 Anexo I como referencia', frecuencia: 'Por formulación' },
      ],
      pp: [{ ensayo: 'Migración global PP', norma: 'RTCA 67.01.33:06', frecuencia: 'Por lote' }],
    },
    normas_seg: { mecanico: 'RTCA 65.01.53:08 / ISO 8124-1', inflamabilidad: 'RTCA 65.01.53:08 / EN 71-2', elementos: 'RTCA 65.01.53:08 / EN 71-3', bordes: 'RTCA 65.01.53:08 / ISO 8124-1' },
  },
};

// ── UI Labels (3 languages) ──────────────────────────────────────────────────
const LABELS = {
  en: {
    title_doc: 'TECHNICAL FILE', confidential: 'CONFIDENTIAL — For internal use and market surveillance authorities',
    s1: 'Product identification', s2: 'Technical product description',
    s2_1: '2.1 General description', s2_2: '2.2 Intended use',
    s2_3: '2.3 Foreseeable misuse', s2_4: '2.4 Components and materials',
    s3: 'Applicable regulatory framework', s3_1: '3.1 Food contact materials (FCM)',
    s3_2: '3.2 Toy / product safety', s3_3: '3.3 Electrical safety', s3_4: '3.4 Hazardous substances',
    s4: 'Risk assessment', s5: 'Required tests and studies',
    s5_1: '5.1 FCM / Migration tests', s5_2: '5.2 Product safety tests', s5_3: '5.3 Electrical tests',
    s6: 'Technical file documentation', s7: 'Mandatory labelling',
    s7_1: '7.1 General labelling requirements', s7_2: '7.2 Mandatory safety warnings',
    s8: 'Non-conformity management', s9: 'Recommended actions',
    s10: 'Version control', s11: 'Declaration and signature',
    campo: 'Field', detalle: 'Detail', componente: 'Component', material: 'Material', contacto: 'Food contact',
    riesgo: 'Identified risk', nivel_ini: 'Initial level', medida: 'Control measure', nivel_res: 'Residual level',
    ensayo: 'Test', norma: 'Standard / Reference', frecuencia: 'Frequency',
    doc_num: '#', doc_doc: 'Document', estado: 'Status', incluido: 'Included', pendiente: 'Pending',
    situacion: 'Situation', accion_req: 'Required action', prioridad: 'Priority',
    criticidad: 'Severity', nc_intro: 'The following table identifies foreseeable non-conformity situations, their severity level, and the corrective actions to be applied. All non-conformities must be documented, investigated, and resolved before the product is placed on the market or before resuming its distribution.',
    accion: 'Action', responsable: 'Responsible', plazo: 'Timeline',
    version: 'Version', fecha: 'Date', autor: 'Author', cambios: 'Changes',
    nota_riesgos: 'Risks identified based on declared materials, product characteristics and applicable regulations.',
    nota_ensayos: 'Tests required per applicable regulations for declared materials. Verify with ISO 17025 accredited laboratory for the specific market.',
    nombre_com: 'Trade name', tipo_prod: 'Product type', ref_int: 'Internal reference',
    ver_doc: 'Document version', fecha_em: 'Issue date', mercado: 'Target market',
    canal: 'Distribution channel', publico: 'Target audience', resp_tec: 'Technical responsible',
    firma_nombre: 'Name:', firma_cargo: 'Title:', firma_empresa: 'Company:', firma_fecha: 'Date:', firma_firma: 'Signature:',
    warning_label: 'WARNING', prio_alto: 'HIGH', prio_medio: 'MEDIUM', prio_bajo: 'LOW',
    nivel_alto: 'HIGH', nivel_medio: 'MEDIUM', nivel_bajo: 'LOW',
    market_label: 'Market', version_label: 'Version',
    por_definir: '[To be defined]',
  },
  es: {
    title_doc: 'EXPEDIENTE TÉCNICO', confidential: 'CONFIDENCIAL - Para uso interno y autoridades de vigilancia de mercado',
    s1: 'Identificación del producto', s2: 'Descripción técnica del producto',
    s2_1: '2.1 Descripción general', s2_2: '2.2 Uso previsto',
    s2_3: '2.3 Usos indebidos previsibles', s2_4: '2.4 Componentes y materiales',
    s3: 'Marco regulatorio aplicable', s3_1: '3.1 Materiales en contacto con alimentos (MOCA)',
    s3_2: '3.2 Seguridad de juguetes / producto', s3_3: '3.3 Seguridad eléctrica', s3_4: '3.4 Sustancias peligrosas',
    s4: 'Evaluación de riesgos', s5: 'Ensayos y pruebas requeridas',
    s5_1: '5.1 Ensayos MOCA', s5_2: '5.2 Ensayos de seguridad del producto', s5_3: '5.3 Ensayos eléctricos',
    s6: 'Documentación del expediente técnico', s7: 'Etiquetado obligatorio',
    s7_1: '7.1 Requisitos generales de etiquetado', s7_2: '7.2 Advertencias de seguridad obligatorias',
    s8: 'Gestión de no conformidades', s9: 'Acciones recomendadas',
    s10: 'Control de versiones', s11: 'Declaración y firma',
    campo: 'Campo', detalle: 'Detalle', componente: 'Componente', material: 'Material', contacto: 'Contacto con alimento',
    riesgo: 'Riesgo identificado', nivel_ini: 'Nivel inicial', medida: 'Medida de control', nivel_res: 'Nivel residual',
    ensayo: 'Ensayo', norma: 'Norma / Referencia', frecuencia: 'Frecuencia',
    doc_num: '#', doc_doc: 'Documento', estado: 'Estado', incluido: 'Incluido', pendiente: 'Pendiente',
    situacion: 'Situación', accion_req: 'Acción requerida', prioridad: 'Prioridad',
    criticidad: 'Criticidad', nc_intro: 'La siguiente tabla identifica situaciones de no conformidad previsibles, su nivel de criticidad y las acciones correctivas a aplicar. Toda no conformidad debe ser documentada, investigada y resuelta antes de la comercialización del producto o antes de reanudar su distribución.',
    accion: 'Acción', responsable: 'Responsable', plazo: 'Plazo',
    version: 'Versión', fecha: 'Fecha', autor: 'Autor', cambios: 'Cambios',
    nota_riesgos: 'Riesgos identificados con base en materiales declarados, características del producto y normativa aplicable.',
    nota_ensayos: 'Ensayos requeridos según normativa aplicable para los materiales declarados. Verificar con laboratorio acreditado ISO 17025 para el mercado específico.',
    nombre_com: 'Nombre comercial', tipo_prod: 'Tipo de producto', ref_int: 'Referencia interna',
    ver_doc: 'Versión del documento', fecha_em: 'Fecha de emisión', mercado: 'Mercado de destino',
    canal: 'Canal de distribución', publico: 'Público objetivo', resp_tec: 'Responsable técnico',
    firma_nombre: 'Nombre:', firma_cargo: 'Cargo:', firma_empresa: 'Empresa:', firma_fecha: 'Fecha:', firma_firma: 'Firma:',
    warning_label: 'ADVERTENCIA', prio_alto: 'ALTO', prio_medio: 'MEDIO', prio_bajo: 'BAJO',
    nivel_alto: 'ALTO', nivel_medio: 'MEDIO', nivel_bajo: 'BAJO',
    market_label: 'Mercado', version_label: 'Versión',
    por_definir: '[Por definir]',
  },
  pt: {
    title_doc: 'DOSSIÊ TÉCNICO', confidential: 'CONFIDENCIAL — Para uso interno e autoridades de vigilancia de mercado',
    s1: 'Identificacao do produto', s2: 'Descricao tecnica do produto',
    s2_1: '2.1 Descricao geral', s2_2: '2.2 Uso previsto',
    s2_3: '2.3 Usos indevidos previsiveis', s2_4: '2.4 Componentes e materiais',
    s3: 'Marco regulatorio aplicavel', s3_1: '3.1 Materiais em contato com alimentos (MOCA)',
    s3_2: '3.2 Seguranca de brinquedos / produto', s3_3: '3.3 Seguranca eletrica', s3_4: '3.4 Substancias perigosas',
    s4: 'Avaliacao de riscos', s5: 'Ensaios e testes requeridos',
    s5_1: '5.1 Ensaios MOCA / Migracao', s5_2: '5.2 Ensaios de seguranca do produto', s5_3: '5.3 Ensaios eletricos',
    s6: 'Documentacao do dossie tecnico', s7: 'Rotulagem obrigatoria',
    s7_1: '7.1 Requisitos gerais de rotulagem', s7_2: '7.2 Advertencias de seguranca obrigatorias',
    s8: 'Gestao de nao conformidades', s9: 'Acoes recomendadas',
    s10: 'Controle de versoes', s11: 'Declaracao e assinatura',
    campo: 'Campo', detalle: 'Detalhe', componente: 'Componente', material: 'Material', contacto: 'Contato com alimento',
    riesgo: 'Risco identificado', nivel_ini: 'Nivel inicial', medida: 'Medida de controle', nivel_res: 'Nivel residual',
    ensayo: 'Ensaio', norma: 'Norma / Referencia', frecuencia: 'Frequencia',
    doc_num: '#', doc_doc: 'Documento', estado: 'Status', incluido: 'Incluido', pendiente: 'Pendente',
    situacion: 'Situacao', accion_req: 'Acao requerida', prioridad: 'Prioridade',
    criticidad: 'Criticidade', nc_intro: 'A tabela a seguir identifica situacoes de nao conformidade previsiveis, seu nivel de criticidade e as acoes corretivas a aplicar. Toda nao conformidade deve ser documentada, investigada e resolvida antes da comercializacao do produto ou antes de retomar sua distribuicao.',
    accion: 'Acao', responsable: 'Responsavel', plazo: 'Prazo',
    version: 'Versao', fecha: 'Data', autor: 'Autor', cambios: 'Alteracoes',
    nota_riesgos: 'Riscos identificados com base nos materiais declarados, caracteristicas do produto e regulamentos aplicaveis.',
    nota_ensayos: 'Ensaios exigidos pela regulamentacao aplicavel para os materiais declarados. Verificar com laboratorio acreditado ISO 17025 para o mercado especifico.',
    nombre_com: 'Nome comercial', tipo_prod: 'Tipo de produto', ref_int: 'Referencia interna',
    ver_doc: 'Versao do documento', fecha_em: 'Data de emissao', mercado: 'Mercado de destino',
    canal: 'Canal de distribuicao', publico: 'Publico-alvo', resp_tec: 'Responsavel tecnico',
    firma_nombre: 'Nome:', firma_cargo: 'Cargo:', firma_empresa: 'Empresa:', firma_fecha: 'Data:', firma_firma: 'Assinatura:',
    warning_label: 'ADVERTENCIA', prio_alto: 'ALTO', prio_medio: 'MEDIO', prio_bajo: 'BAIXO',
    nivel_alto: 'ALTO', nivel_medio: 'MEDIO', nivel_bajo: 'BAIXO',
    market_label: 'Mercado', version_label: 'Versao',
    por_definir: '[A definir]',
  },
};

// ── Category name translations ────────────────────────────────────────────────
const CATEGORY_TRANSLATIONS = {
  en: {
    'Contenedor de alimentos':         'Food container',
    'Vaso / Taza':                     'Cup / Mug',
    'Plato / Bowl':                    'Plate / Bowl',
    'Utensilio de cocina':             'Kitchen utensil',
    'Envase de alimentos':             'Food packaging',
    'Juguete con función alimentaria': 'Toy with food function',
    'Accesorio de cocina':             'Kitchen accessory',
    'Set de utensilios':               'Utensils set',
  },
  pt: {
    'Contenedor de alimentos':         'Recipiente para alimentos',
    'Vaso / Taza':                     'Copo / Caneca',
    'Plato / Bowl':                    'Prato / Tigela',
    'Utensilio de cocina':             'Utensílio de cozinha',
    'Envase de alimentos':             'Embalagem de alimentos',
    'Juguete con función alimentaria': 'Brinquedo com função alimentar',
    'Accesorio de cocina':             'Acessório de cozinha',
    'Set de utensilios':               'Conjunto de utensílios',
  },
};
function translateCategory(cat, idioma) {
  if (!idioma || idioma === 'es') return cat;
  return (CATEGORY_TRANSLATIONS[idioma] && CATEGORY_TRANSLATIONS[idioma][cat]) || cat;
}

// ── Product Characteristics Options ─────────────────────────────────────────
const CHARACTERISTICS = [
  // ── Clasificación general ──
  { id: 'juguete',          label: 'Categoría juguete / toy',           group: 'general' },
  { id: 'ninos',            label: 'Dirigido a niños (< 14 años)',       group: 'general' },
  { id: 'food_direct',      label: 'Contacto directo con alimentos',     group: 'general' },
  { id: 'plastico',         label: 'Material plástico',                  group: 'general' },
  { id: 'multicolor',       label: 'Pintura / colores múltiples',        group: 'general' },
  // ── Peligros mecánicos (EN 71-1 / ASTM F963) ──
  { id: 'disenio_3d',       label: 'Diseño 3D / figura decorativa',      group: 'mecanico' },
  { id: 'bordes_filosos',   label: 'Bordes o puntas filosas / cortantes',group: 'mecanico' },
  { id: 'partes_pequenas',  label: 'Partes pequeñas (Ø < 31.7 mm)',      group: 'mecanico' },
  { id: 'piezas_moviles',   label: 'Piezas móviles / articuladas',       group: 'mecanico' },
  { id: 'imanes',           label: 'Imanes / elementos magnéticos',      group: 'mecanico' },
  { id: 'cuerdas',          label: 'Cuerdas, cordones o elásticos',      group: 'mecanico' },
  { id: 'proyectiles',      label: 'Lanza proyectiles / partes volantes',group: 'mecanico' },
  { id: 'liquidos',         label: 'Contiene líquidos / gel',            group: 'mecanico' },
  // ── Peligros eléctricos / térmicos ──
  { id: 'electronico',      label: 'Componente electrónico',             group: 'electrico' },
  { id: 'bateria',          label: 'Pila / batería / USB cargable',      group: 'electrico' },
  { id: 'bateria_boton',    label: 'Pila botón / moneda (coin cell)',     group: 'electrico' },
  { id: 'led',              label: 'LEDs / iluminación',                 group: 'electrico' },
  { id: 'vapor',            label: 'Generador de vapor / calor',         group: 'electrico' },
  // ── Peligros acústicos ──
  { id: 'ruido',            label: 'Genera ruido / sonidos > 80 dB',     group: 'acustico' },
];

// ── Docs Checklist ───────────────────────────────────────────────────────────
const DOCS_CHECKLIST = {
  en: [
    ['Technical product description (this document)', true],
    ['Technical design specifications / 3D renders / drawings', false],
    ['Bill of materials (BOM) with supplier technical data sheets', false],
    ['Supplier declarations of conformity for raw materials', false],
    ['Laboratory reports — FCM migration (overall and specific)', false],
    ['Laboratory reports — toy / product safety', false],
    ['Risk assessment (Section 4 of this document)', true],
    ['{DOC}', false],
    ['Instructions for use in the language of the target market', false],
    ['Product label — final artwork proof', false],
    ['Production batch traceability', false],
  ],
  es: [
    ['Descripcion tecnica del producto (este documento)', true],
    ['Especificaciones tecnicas de diseno / renders 3D / planos', false],
    ['Lista de materiales (BOM) con fichas tecnicas de proveedores', false],
    ['Declaraciones de conformidad de proveedores de materia prima', false],
    ['Informes de laboratorio MOCA — migracion global y especifica', false],
    ['Informes de laboratorio — seguridad de juguetes / producto', false],
    ['Evaluacion de riesgos (Seccion 4 de este documento)', true],
    ['{DOC}', false],
    ['Manual / instrucciones de uso en idioma del mercado de destino', false],
    ['Etiqueta del producto — prueba de arte definitiva', false],
    ['Trazabilidad del lote de produccion', false],
  ],
  pt: [
    ['Descricao tecnica do produto (este documento)', true],
    ['Especificacoes tecnicas de design / renders 3D / plantas', false],
    ['Lista de materiais (BOM) com fichas tecnicas dos fornecedores', false],
    ['Declaracoes de conformidade dos fornecedores de materias-primas', false],
    ['Relatorios de laboratorio MOCA — migracao global e especifica', false],
    ['Relatorios de laboratorio — seguranca de brinquedos / produto', false],
    ['Avaliacao de riscos (Secao 4 deste documento)', true],
    ['{DOC}', false],
    ['Manual / instrucoes de uso no idioma do mercado de destino', false],
    ['Rotulo do produto — prova de arte definitiva', false],
    ['Rastreabilidade do lote de producao', false],
  ],
};

// ── Label Requirements por país ───────────────────────────────────────────────
const LABEL_GROUPS = {
  Internacional: { label: 'Internacional 🌐', countries: ['UE','USA','Australia'] },
  LATAM:         { label: 'LATAM 🌎',         countries: ['Brasil','Colombia','Argentina','Peru'] },
  CAM:           { label: 'Centroamérica 🌎',  countries: ['Guatemala','El Salvador','Honduras','Nicaragua','Costa Rica','Panama'] },
};

const LABEL_REQUIREMENTS = {
  UE: { flag:'🇪🇺', nombre:'Unión Europea', reqs:[
    { id:'ce_mark',           label:'Marcado CE',                                           ref:'Dir. 2009/48/EC / LVD 2014/35/EU',        cond:'always'        },
    { id:'fcm_symbol',        label:'Símbolo FCM (tenedor + vaso)',                          ref:'Reg. (CE) 1935/2004 Art. 15',             cond:'food'          },
    { id:'country_origin',    label:'País de origen ("Made in ___")',                        ref:'EU Customs Code / EUTR',                  cond:'always'        },
    { id:'manufacturer',      label:'Fabricante o importador EU (nombre + dirección)',       ref:'Dir. 2009/48/EC Art. 11',                 cond:'always'        },
    { id:'batch',             label:'Número de lote / referencia de trazabilidad',           ref:'Dir. 2009/48/EC Art. 11',                 cond:'always'        },
    { id:'age_warning',       label:'Advertencia de edad mínima',                            ref:'Dir. 2009/48/EC Annex V / EN 71',         cond:'children'      },
    { id:'choking',           label:'Advertencia de asfixia (piezas pequeñas)',              ref:'Dir. 2009/48/EC Annex V',                 cond:'children'      },
    { id:'weee',              label:'Símbolo WEEE (contenedor tachado)',                     ref:'Dir. 2012/19/EU',                         cond:'elec'          },
    { id:'rohs_compliance',   label:'Declaración conformidad RoHS',                          ref:'Dir. 2011/65/EU (RoHS2)',                 cond:'elec'          },
    { id:'battery_disposal',  label:'Símbolo + texto eliminación de baterías',               ref:'Dir. 2006/66/EC / EU Reg. 2023/1542',    cond:'battery'       },
    { id:'button_battery_warn',label:'Advertencia batería botón — riesgo ingesta/asfixia',  ref:'EU Reg. 2023/1542 Annex VI',             cond:'button_battery'},
    { id:'melamine_temp_limit',label:'Límite de temperatura y restricciones de uso',         ref:'EU Reg. 10/2011 / DIN 68830',            cond:'melamine'      },
    { id:'reach_pvc',         label:'Declaración sin ftalatos restringidos (REACH)',          ref:'Reg. (CE) 1907/2006 REACH / SVHC',      cond:'pvc'           },
    { id:'steam_warning',     label:'Advertencia quemaduras por vapor',                      ref:'Dir. 2014/68/EU / EN 12778',             cond:'steam'         },
    { id:'noise_warning',     label:'Advertencia daño auditivo (>80 dB)',                    ref:'EN 71-1 §4.5 / Dir. 2009/48/EC',        cond:'noise'         },
    { id:'string_warning',    label:'Advertencia estrangulamiento por cuerdas',               ref:'EN 71-1 §4.16-4.17 / Dir. 2009/48/EC',  cond:'strings'       },
    { id:'magnet_warning',    label:'Advertencia implantes magnéticos / marcapasos',          ref:'EN 71-1 §4.28 / Dir. 2009/48/EC',       cond:'magnets'       },
    { id:'suffocation',       label:'Advertencia de asfixia en polybag/bolsa plástica',     ref:'Dir. 2009/48/EC / EN 71',                 cond:'always'        },
    { id:'language',          label:'Instrucciones y advertencias en idioma(s) EU',          ref:'Dir. 2009/48/EC Art. 11',                 cond:'always'        },
  ]},
  USA: { flag:'🇺🇸', nombre:'Estados Unidos', reqs:[
    { id:'cpsia_tracking',    label:'CPSIA tracking label (producto + empaque)',              ref:'CPSIA Sec. 103 / 16 CFR 1130',           cond:'children'      },
    { id:'prop65',            label:'California Prop 65 WARNING',                             ref:'CA Health & Safety Code §25249.6',       cond:'always'        },
    { id:'country_origin',    label:'País de origen ("Made in ___")',                         ref:'19 U.S.C. 1304 (Tariff Act)',            cond:'always'        },
    { id:'manufacturer',      label:'Fabricante o importador USA (nombre)',                   ref:'CPSIA / FTC',                            cond:'always'        },
    { id:'age_warning',       label:'Advertencia de edad y supervisión adulta',               ref:'CPSC / ASTM F963-23',                    cond:'children'      },
    { id:'choking',           label:'CHOKING HAZARD — piezas pequeñas < 3 años',             ref:'16 CFR 1500.19 / ASTM F963',             cond:'children'      },
    { id:'fcc_id',            label:'FCC ID visible en empaque o producto',                   ref:'47 CFR §15.19(a)(3)',                    cond:'elec'          },
    { id:'battery_disposal',  label:'Instrucción reciclaje batería / Call2Recycle',           ref:'RCRA / EPA / Call2Recycle program',      cond:'battery'       },
    { id:'button_battery_warn',label:'Advertencia batería botón (texto requerido CPSC)',      ref:'CPSC / ASTM F963-23 §4.25 / 16 CFR',   cond:'button_battery'},
    { id:'melamine_temp_limit',label:'"Not microwave safe" / límite temperatura melamina',    ref:'FDA / CPSC melamine guidance',           cond:'melamine'      },
    { id:'steam_warning',     label:'Advertencia quemaduras por vapor',                       ref:'CPSC / ASTM F2285',                     cond:'steam'         },
    { id:'noise_warning',     label:'Advertencia daño auditivo',                              ref:'CPSC / ASTM F963-23 §4.5',             cond:'noise'         },
    { id:'string_warning',    label:'Advertencia cuerdas/estrangulamiento',                   ref:'CPSC / 16 CFR 1500.49-52',             cond:'strings'       },
    { id:'suffocation',       label:'Advertencia de asfixia en polybag',                     ref:'ASTM F3069 / industry practice',          cond:'always'        },
    { id:'fda_food',          label:'Declaración conformidad FDA (contacto alimentos)',       ref:'21 CFR 177 / FDA FCS Program',           cond:'food'          },
    { id:'barcode',           label:'Código de barras UPC',                                   ref:'GS1 / retail requirement',               cond:'always'        },
  ]},
  Australia: { flag:'🇦🇺', nombre:'Australia', reqs:[
    { id:'country_origin',    label:'País de origen',                                         ref:'Australian Consumer Law (ACL) §255',     cond:'always'        },
    { id:'manufacturer',      label:'Importador australiano (nombre + dirección)',             ref:'ACL §255 / ACCC',                        cond:'always'        },
    { id:'age_warning',       label:'Advertencia de edad mínima',                             ref:'AS/NZS ISO 8124 / ACCC',                 cond:'children'      },
    { id:'choking',           label:'Advertencia de asfixia (piezas pequeñas)',               ref:'ACCC mandatory warning',                 cond:'children'      },
    { id:'button_battery_warn',label:'Advertencia batería botón (texto ACCC obligatorio)',    ref:'ACCC Button Battery Mandatory Std 2022', cond:'button_battery'},
    { id:'battery_disposal',  label:'Instrucción eliminación de baterías',                    ref:'ACCC / Battery Stewardship Council',    cond:'battery'       },
    { id:'steam_warning',     label:'Advertencia quemaduras por vapor',                       ref:'ACCC / AS/NZS standards',               cond:'steam'         },
    { id:'noise_warning',     label:'Advertencia daño auditivo',                              ref:'ACCC / AS/NZS 8124',                   cond:'noise'         },
    { id:'string_warning',    label:'Advertencia estrangulamiento por cuerdas',               ref:'ACCC / AS/NZS 8124 §4.16',             cond:'strings'       },
    { id:'suffocation',       label:'Advertencia de asfixia en polybag',                     ref:'ACCC / industry practice',               cond:'always'        },
    { id:'language',          label:'Instrucciones y advertencias en inglés',                 ref:'ACL',                                    cond:'always'        },
  ]},
  Brasil: { flag:'🇧🇷', nombre:'Brasil', reqs:[
    { id:'inmetro',           label:'Marca o registro INMETRO',                               ref:'Lei 9.933/1999 / Portarias INMETRO',     cond:'always'        },
    { id:'country_origin',    label:'País de fabricação ("Fabricado em ___")',                ref:'Código de Defesa do Consumidor Art. 31', cond:'always'        },
    { id:'importer',          label:'Importador brasileño (nombre + CNPJ)',                   ref:'CDC Art. 31',                            cond:'always'        },
    { id:'language',          label:'Instrucciones y advertencias en portugués',              ref:'CDC Art. 31',                            cond:'always'        },
    { id:'anvisa',            label:'Registro ANVISA (contacto alimentos)',                   ref:'RDC ANVISA 331/2019',                    cond:'food'          },
    { id:'age_warning',       label:'Advertencia de edad (português)',                        ref:'Portaria INMETRO 563/2016',              cond:'children'      },
    { id:'battery_disposal',  label:'Instrucción reciclaje batería (CONAMA 401)',             ref:'CONAMA Res. 401/2008 / ABNT NBR 14725', cond:'battery'       },
    { id:'button_battery_warn',label:'Advertencia batería botón (riesgo de ingestión)',      ref:'INMETRO / ABNT',                        cond:'button_battery'},
    { id:'melamine_temp_limit',label:'Advertência de temperatura melamina (em português)',   ref:'ANVISA RDC 51/2010',                    cond:'melamine'      },
    { id:'barcode',           label:'Código de barras EAN',                                   ref:'GS1 Brazil',                            cond:'always'        },
  ]},
  Colombia: { flag:'🇨🇴', nombre:'Colombia', reqs:[
    { id:'country_origin',    label:'País de origen',                                         ref:'Res. SIC 60519/2014',                    cond:'always'        },
    { id:'importer',          label:'Importador colombiano (nombre + NIT)',                   ref:'Decreto 975/2014',                       cond:'always'        },
    { id:'language',          label:'Instrucciones y advertencias en español',               ref:'Res. SIC',                               cond:'always'        },
    { id:'invima',            label:'Registro INVIMA (contacto alimentos)',                   ref:'Decreto 4444/2005',                      cond:'food'          },
    { id:'icontec',           label:'Certificación ICONTEC (juguetes)',                       ref:'NTC 4894',                               cond:'toy'           },
    { id:'age_warning',       label:'Advertencia de edad',                                   ref:'NTC 4894 / SIC',                         cond:'children'      },
    { id:'battery_disposal',  label:'Instrucción eliminación/reciclaje de batería',           ref:'Decreto 1076/2015 (MADS)',               cond:'battery'       },
    { id:'button_battery_warn',label:'Advertencia batería botón',                            ref:'SIC / Res. Min. Ambiente',              cond:'button_battery'},
    { id:'noise_warning',     label:'Advertencia daño auditivo',                              ref:'SIC / NTC 4894 §4.5',                  cond:'noise'         },
    { id:'string_warning',    label:'Advertencia estrangulamiento por cuerdas',               ref:'NTC 4894 §4.16',                        cond:'strings'       },
  ]},
  Argentina: { flag:'🇦🇷', nombre:'Argentina', reqs:[
    { id:'country_origin',    label:'País de origen',                                         ref:'Ley 24.240 / SENASA',                    cond:'always'        },
    { id:'importer',          label:'Importador argentino (nombre + CUIT)',                   ref:'Ley 24.240 Art. 10',                     cond:'always'        },
    { id:'language',          label:'Instrucciones y advertencias en español',               ref:'Ley 24.240 Art. 10',                     cond:'always'        },
    { id:'anmat',             label:'Autorización ANMAT (contacto alimentos)',               ref:'Disp. ANMAT 4980/2005',                  cond:'food'          },
    { id:'iram',              label:'Certificación IRAM (juguetes)',                         ref:'IRAM-ISO 8124',                          cond:'toy'           },
    { id:'age_warning',       label:'Advertencia de edad',                                   ref:'IRAM-ISO 8124 / Disp. ANMAT',            cond:'children'      },
    { id:'battery_disposal',  label:'Instrucción eliminación de pilas/baterías',             ref:'Ley 24.051 / SAyDS',                     cond:'battery'       },
    { id:'button_battery_warn',label:'Advertencia batería botón',                            ref:'ANMAT / SAyDS',                         cond:'button_battery'},
    { id:'noise_warning',     label:'Advertencia daño auditivo',                              ref:'IRAM-ISO 8124 §4.5',                    cond:'noise'         },
    { id:'string_warning',    label:'Advertencia estrangulamiento por cuerdas',               ref:'IRAM-ISO 8124 §4.16',                   cond:'strings'       },
  ]},
  Peru: { flag:'🇵🇪', nombre:'Perú', reqs:[
    { id:'country_origin',    label:'País de origen',                                         ref:'D.L. 807 INDECOPI / Ley 29571',          cond:'always'        },
    { id:'importer',          label:'Importador peruano (nombre + RUC)',                     ref:'Ley 29571 Art. 2',                       cond:'always'        },
    { id:'language',          label:'Instrucciones y advertencias en español',               ref:'Ley 29571',                              cond:'always'        },
    { id:'digesa',            label:'Registro DIGESA (contacto alimentos)',                   ref:'D.S. 007-98-SA',                         cond:'food'          },
    { id:'age_warning',       label:'Advertencia de edad',                                   ref:'NTP-ISO 8124 INDECOPI',                  cond:'children'      },
    { id:'battery_disposal',  label:'Instrucción eliminación de pilas/baterías',             ref:'D.L. 1278 / MINAM',                      cond:'battery'       },
    { id:'button_battery_warn',label:'Advertencia batería botón',                            ref:'INDECOPI / OEFA',                        cond:'button_battery'},
    { id:'noise_warning',     label:'Advertencia daño auditivo',                              ref:'NTP-ISO 8124 §4.5 / INDECOPI',          cond:'noise'         },
    { id:'string_warning',    label:'Advertencia estrangulamiento por cuerdas',               ref:'NTP-ISO 8124 §4.16 / INDECOPI',         cond:'strings'       },
  ]},
  Guatemala:     { flag:'🇬🇹', nombre:'Guatemala',    reqs: null },
  'El Salvador': { flag:'🇸🇻', nombre:'El Salvador',  reqs: null },
  Honduras:      { flag:'🇭🇳', nombre:'Honduras',     reqs: null },
  Nicaragua:     { flag:'🇳🇮', nombre:'Nicaragua',    reqs: null },
  'Costa Rica':  { flag:'🇨🇷', nombre:'Costa Rica',   reqs: null },
  Panama:        { flag:'🇵🇦', nombre:'Panamá',       reqs: null },
};

// CAM countries share RTCA requirements
['Guatemala','El Salvador','Honduras','Nicaragua','Costa Rica','Panama'].forEach(c => {
  LABEL_REQUIREMENTS[c].reqs = [
    { id:'country_origin',     label:'País de origen',                                        ref:'RTCA 23.01.33:06',                       cond:'always'        },
    { id:'importer',           label:'Importador local (nombre + dirección)',                 ref:'Ley de Protección al Consumidor',         cond:'always'        },
    { id:'language',           label:'Instrucciones y advertencias en español',               ref:'RTCA / Ley local',                       cond:'always'        },
    { id:'rtca_toys',          label:'Declaración cumplimiento RTCA (juguetes)',              ref:'RTCA 71.03.47:07',                       cond:'toy'           },
    { id:'age_warning',        label:'Advertencia de edad y seguridad',                      ref:'RTCA 71.03.47:07',                       cond:'children'      },
    { id:'choking',            label:'Advertencia de asfixia (piezas pequeñas)',             ref:'RTCA 71.03.47:07 / Ley local',           cond:'children'      },
    { id:'battery_disposal',   label:'Instrucción eliminación de baterías',                  ref:'Legislación ambiental local',             cond:'battery'       },
    { id:'button_battery_warn',label:'Advertencia batería botón (riesgo de ingestión)',      ref:'RTCA / legislación local',               cond:'button_battery'},
    { id:'noise_warning',      label:'Advertencia daño auditivo (juguetes con sonido)',      ref:'RTCA 71.03.47:07 §4.5',                 cond:'noise'         },
    { id:'string_warning',     label:'Advertencia estrangulamiento por cuerdas',              ref:'RTCA 71.03.47:07 §4.16',                cond:'strings'       },
    { id:'suffocation',        label:'Advertencia de asfixia en polybag',                    ref:'RTCA / industry practice',               cond:'always'        },
  ];
});
